[package]

name = "simproc"
version = "0.1.0"
authors = ["Alvaro Polo <apoloval@gmail.com>"]

[dependencies]
docopt = "0.6.40"
regex = "0.1.8"
regex_macros = "0.1.8"
rustc-serialize = "0.3.0"

[lib]
name = "simproc"

[[bin]]
name = "spasm"
path = "src/bin/spasm/main.rs"
